<?php

/* * ********************************************************************
 * Customization Services by ModulesGarden.com
 * Copyright (c) ModulesGarden, INBS Group Brand, All Rights Reserved 
 * (2014-05-16, 11:24:43)
 * 
 *
 *  CREATED BY MODULESGARDEN       ->        http://modulesgarden.com
 *  CONTACT                        ->       contact@modulesgarden.com
 *
 *
 *
 *
 * This software is furnished under a license and may be used and copied
 * only  in  accordance  with  the  terms  of such  license and with the
 * inclusion of the above copyright notice.  This software  or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person.  No title to and  ownership of the  software is  hereby
 * transferred.
 *
 *
 * ******************************************************************** */

/**
 * @author Grzegorz Draganik <grzegorz@modulesgarden.com>
 */
?>

<div class="modulesgarden_grid_container">
	<div class="content-header <?php echo $this->getSkipHeaderCopy() ? 'skip-header' : ''; ?>">
		<table cellspacing="0">
			<tr>
				<td style="<?php echo $this->getHeaderWidth() ?>"><?php echo $this->getHeaderHtml() ?></td>
				<td class="form-buttons"><?php echo $this->getButtonsHtml() ?></td>
			</tr>
		</table>
	</div>
	<div>
		<?php echo $this->getGridHtml() ?>
	</div>
</div>