var rootModule;
var controllersModule;
var inkyAppController;
var siteUrl = site_url;
var sitePath = site_path;
var clipArtPath = clip_art_path;
var defaultClipColor = "";
var textColorTitle;
var clipColorTitle;
var editData;
var onlyOneTimeRotFlag = true;
var canvas;
var premoveX;
var xinterVal;
var premoveY;
var cartNavigationUrl;
var previousWidthSizePrice = 0;
var previousHeightSizePrice = 0;
var useSizeData;
var singleStichingColor = "EOEOEO";
var singleStichingColorID = 0;
var singleStichingColorTitle = "";
var sendChineseData;
var selectedSizeObj;
var preColorSelectedItem;
var leaveColorTextureFlag = true;
var textColorId;
var clipColorId;
var preventDuplicateFlag = true;
var saveEventType;
var strapSelectedIndx = 0;
var canvasSelectionFlag = "design";
var designDataArrayCounter = 0;
var designDataLayerCounter = 0;
var selectedCanvas;
var strapStyleData = new Array;
var globalVar = 0;
var textureFlag = true;
var navigationFlag = true;
var smallMobileDeviceFlag = false;
var dragImageCounter = 0;
var promiseDataArr = new Array;
var promiseDataArrCounter = 0;
var dragX;
var dragY;
var imageLeft = 0;
var globalViewCounter = 0;
var imageTop = 0;
var optionsSizesArr = new Array;
var optionId = 0;
var optionColorPrice = 0;
var sendPriceInfoArr;
var objPreventFlag = false;
var drawNextDiffWidth;
var previewArr = new Array;
var canvasArr = new Array;
var globalSelectedItem;
var clickEventType = document.ontouchstart !== null ? "click" : "touchstart";
var downEvent = document.ontouchstart !== null ? "mousedown" : "touchstart";
var upEvent = document.ontouchstart !== null ? "mouseup" : "touchend";
var moveEvent = document.ontouchstart !== null ? "mousemove" : "touchmove";
var onderInfoEvent = document.ontouchstart !== null ? "mouseenter" : "touchstart";
var canvasViewArray = new Array;
var productData;
var selectedPartInfoObj;
var productsData;
var mobileMode;
var frontGroupSelected;
var backGroupSelected;
var totalPrice = 0;
var detectArr = new Array;
var selectedPartPrice = 0;
var editMode = mode;
var fabricFontSize = 18;
var fabricImageObjects1 = new Array;
var fabricImageObjects2 = new Array;
var fabricImageObjects3 = new Array;
var fabricImageObjects4 = new Array;
var fabricImageObjects5 = new Array;
var fabricImageObjects6 = new Array;
var fabricImageObjects7 = new Array;
var fabricImageObjects8 = new Array;
var previewCanvas;
var selectedCanvasObjects;
var previewCounter = 0;
var canWidth = 290;
var canHeight = 540;
var previewWidth = 290;
var previeHeight = 540;
var doubleStrapSelectionFlag = false;
var previewRatioX;
var previewRatioY;
var previewRatioPX;
var previewRatioPY;
var dataArray = new Array;
var designDataArr = new Array;
var userInfo = new Object;
var optionsData;
var toplidGrp;
var insidelidGrp;
var partDropDownArr = new Array;
var imageCounter = 0;
var effectCounter = 0;
var pocketCounter = 0;
var editCounter = 0;
var pocketData;
var clipartsCat;
var anglesData;
var pocketStyleData;
var pocketsData;
var currentView = 0;
var boldClick = false;
var italicClick = false;
var textAlign = "left";
var setInter;
var fontTitle = "";
var colorPickerValue;
var clipartColors;
var artColorSelectedIndx = 0;
var fontsData;
var fontsSize;
var shapeType;
var selectedTextFont = "";
var selectedFontIndx = 0;
var selectedFontSize = "";
var selectedFontSizeIndx = 0;
var fontStyle = document.createElement("STYLE");
var fontCounter = 0;
var viewCounter = 0;
var nextCounter = 0;
var layerCounter = 0;
var productPartData;
var selectedPartLayersInfo;
var editSelectedPartLayersInfo;
var partLeftPos = 0;
var designCan;
var partTopPos = 0;
var partTitle;
var groupTitle;
var otherPartLoadTitle = "ShoulderPad";
var outputCan;
var styleDesignCode = "";
var productId = 0;
var preventFlag = true;
var handleStyleData;
var img1 = new Array;
var img2 = new Array;
var img3 = new Array;
var img4 = new Array;
var img5 = new Array;
var img6 = new Array;
var img7 = new Array;
var img8 = new Array;
var pocketTitleName = "";
var originalWidth = 358;
var originalHeight = 1326;
var ratioWidth = 118;
var ratioHeight = 440;
var selectedPartIndx = 0;
var textColor;
var textColors;
var textColorSelectedIndx;
var scaleRatioFlag = true;
var scaleRatioWidth;
var scaleRatioHeight;
var loadingPreventFlag;
var dragThumb;
var dragTitle;
var dragPrice;
var dragColorCode;
var dragColorTitle;
var dragColorable;
var dragPartStId;
var dragPartName;
var dragPartPrice;
var dragPartIden;
var dragColorId;
var dragOptionId;
var clipColorPrice = 0;
var textColorPrice = 0;
var printings;
var uploadImageArr = new Array;
var topRightImage = new Image;
topRightImage.src = siteUrl + "assets/images/HImage/rotate.png";
var left_resize = new Image;
left_resize.src = siteUrl + "assets/images/HImage/index.png";
var right_resize = new Image;
right_resize.src = siteUrl + "assets/images/HImage/right-resize11.png";
var bottom_up_resize = new Image;
bottom_up_resize.src = siteUrl + "assets/images/HImage/botom-up-resize.png";
var left_right_resize = new Image;
left_right_resize.src = siteUrl + "assets/images/HImage/left-right.png";
var rotate = new Image;
rotate.src = siteUrl + "assets/images/HImage/rotate.png";
var bottmRightImage = new Image;
bottmRightImage.src = siteUrl + "assets/images/HImage/left-resize1.png";
var rotateCur = siteUrl + "assets/images/HImage/Rotate.cur";
angular.element(document).ready(function() {});
