<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

    google.load('visualization', '1.0', {'packages': ['corechart']});

    // Set a callback to run when the Google Visualization API is loaded.
    google.setOnLoadCallback(drawChart);

    // Callback that creates and populates a data table,
    // instantiates the pie chart, passes in the data and
    // draws it.
    function drawChart() {
        var data = google.visualization.arrayToDataTable([
            ['<?php echo Mage::helper('teamandtaskorganizer')->__('Month') ?>', '<?php echo Mage::helper('teamandtaskorganizer')->__('Total created tasks') ?>', '<?php echo Mage::helper('teamandtaskorganizer')->__('Total finished tasks') ?>']
            <?php foreach($totalTasks as $month=>$tasks): ?>
                ,['<?php echo $month; ?>',<?php echo $tasks['total'],',',$tasks['finished'] ?>]
            <?php endforeach; ?>
        ]);

        var options = {
            //title: '<?php echo Mage::helper('teamandtaskorganizer')->__('Last month tasks') ?>',
            curveType: 'function',
            legend: {
                position: 'bottom'
            }
        };

        var chart = new google.visualization.AreaChart(document.getElementById('statistics_charts'));
        chart.draw(data, options);
    }

</script>

<div id="statistics_charts" style="margin-top: 50px;"></div>
