<?php 
$id = $this->getRequest()->getParam('order_id');
$permission = Mage::helper("orderattachments")->getOrderPermissionStatus();
$attachments = $this->getVisibleOrderAttachments(); 
$customer = Mage::getSingleton('customer/session')->getCustomer();
$customerAllowed = Mage::helper('orderattachments')->getCustomersAllowed($customer);
?>
<div class="page-title">
    <h1><?php echo $this->__('Manage Order Attachments')?></h1>
</div>
<div class="attachments-custom-text">
	<?php echo Mage::helper('orderattachments')->getCustomText();?>
</div>
<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<form action="<?php echo Mage::getUrl('orderattachments/attachment/saveattachments',array('order_id' => $id));?>" method="post" id="form-validate" enctype="multipart/form-data">
	<input type="hidden" name="customer_id" value="<?php echo $customer->getId(); ?>" />
    <table cellspacing="0" class="data-table linearize-table-large" id="order_attachments_grid">
		<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey()?>" />
        <thead>
            <tr class="headings">
                <th class="cell-file"><?php echo $this->__('File') ?></th>
                <th class="cell-comment"><?php echo $this->__('Comment') ?></th>
                <?php  if ($permission['del']): ?>
					<th class="cell-remove last"><?php echo $this->__('Remove') ?></th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody id="order_attachments_list">
            <tr id="row-attachment-template-readonly" class="template no-display">
				<td class="cell-file">
					<a target="_blank" href="#url#" target="_blank">#file_name#</a>
				</td>
				<td class="cell-comment">#comment#</td>
				<?php if ($permission['del']): ?>
					<td class="cell-remove last">
						<div class="onoffswitch ">
							<input type="checkbox" name="order_attachment_#id#[is_delete]" class="onoffswitch-checkbox" id="order-attachment_#id#_is_delete" value="1" />
							<label class="onoffswitch-label" for="order-attachment_#id#_is_delete">
								<span class="onoffswitch-inner"></span>
								<span class="onoffswitch-switch"></span>
							</label>
						</div>
					</td>
				<?php endif; ?>
            </tr>
            <tr id="row-attachment-template-edit" class="template no-display">
				<td class="cell-file">
					<div id="filelist_#id#">Your browser doesn't have Flash, Silverlight or HTML5 support.</div>
					<div id="plupload_progress_container_#id#" class="plupload_progress_container">
						<div class="plupload_progress_bar"></div>
					</div>
					<div id="container_#id#">
						<a id="pickfiles_#id#" href="javascript:;">[Select files]</a> 
						<pre id="console_#id#"></pre>
					</div>
					<a target="_blank" href="#url#">#file_name#</a>
					<input type="hidden" id="file_#id#" name="order_attachment_#id#[file]" value="" /> 
				</td>
				<td class="cell-comment"><textarea class="input-text" rows="5" cols="35" name="order_attachment_#id#[comment]">#comment#</textarea></td>
				<?php if ($permission['del']): ?>
					<td class="cell-remove last">
						<div class="onoffswitch ">
							<input type="checkbox" name="order_attachment_#id#[is_delete]" class="onoffswitch-checkbox" id="order-attachment_#id#_is_delete" value="1" />
							<label class="onoffswitch-label" for="order-attachment_#id#_is_delete">
								<span class="onoffswitch-inner"></span>
								<span class="onoffswitch-switch"></span>
							</label>
						</div>
					</td>
				<?php endif; ?>
				<script type="text/javascript">
				// Custom example logic
				var uploader_;
				var uploaderId = uploader_+'#id#';
				uploaderId = new plupload.Uploader({

					//runtimes : 'html5,flash,silverlight,html4',
					browse_button : 'pickfiles_#id#', // you can pass in id...
					container: document.getElementById('container_#id#'), // ... or DOM Element itself
					url : '<?php echo Mage::getUrl('orderattachments/attachment/show'); ?>',
					
					filters : {
						max_file_size : '<?php echo Mage::helper('orderattachments')->getFileSize(); ?>' + 'mb',
						chunk_size: '1mb',
						mime_types: [
							{title : "Files", extensions : "<?php echo Mage::helper('orderattachments')->getAllowedExtension();?>"},
						]
					},
					
					init: {
						PostInit: function() {
							document.getElementById('filelist_#id#').innerHTML = '';
						},
						FilesAdded: function(up, files) {
							plupload.each(files, function(file) {
								document.getElementById('filelist_#id#').innerHTML = '<div id="' + file.id + '">' + file.name + ' <b></b></div><br/>';
								up.start();
							});
						},
						UploadProgress: function(up, file) {
							document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
							$('plupload_progress_container_#id#').removeClassName("plupload_progress_container");
							$('save-attachments-btn').disable();
							$('save-attachments-btn').addClassName("disabled");
						},
						
						FileUploaded: function(up, file ,info) {
							document.getElementById('file_#id#').value = info.response;
						},
					
						UploadComplete: function(up, files) {
							$('plupload_progress_container_#id#').addClassName("plupload_progress_container");
							$('save-attachments-btn').enable();
							$('save-attachments-btn').removeClassName("disabled");
						},
						Error: function(up, err) {
							document.getElementById('console_#id#').appendChild(document.createTextNode("Error #" + err.code + ": " + err.message +"\n"));
						}
					}
				});
				uploaderId.init();
				</script>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="add-button last">
                    <?php if ($permission['add'] && $customerAllowed): ?>
						<button id="add-attachment" type="button" class="button"><span><span><?php echo $this->__('Add Attachment'); ?></span></span></button>
                    <?php endif; ?>
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getOrderViewBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back to Order View') ?></a></p>
        <?php if(Mage::helper("orderattachments")->getCanSaveAttachmentsForOrder() && $customerAllowed ): ?>
			<button type="submit" id="save-attachments-btn" title="<?php echo $this->__('Save Attachments') ?>" class="button"><span><span><?php echo $this->__('Save Attachments') ?></span></span></button>
        <?php endif; ?>
    </div>
</form>

<script type="text/javascript">
var templateContentEdit = $('row-attachment-template-edit').innerHTML;
var templateContentReadonly = $('row-attachment-template-readonly').innerHTML;
var orderAttachment = {
    div : $('row-attachment-template-edit'),
    addAttachmentBtn: $('add-attachment'),
    templateSyntax : /(^|.|\r|\n)(#(\w+)#)/,
    templateTextEdit : templateContentEdit,
    templateTextReadonly : templateContentReadonly,
    numAllowedAttachments: <?php echo Mage::helper('orderattachments')->getNumOfAllowedAttachment(); ?>  ,
    numAttachments: 0,
    add : function(data) {
        <?php if($permission['edit']): ?>
			this.template = new Template(this.templateTextEdit, this.templateSyntax);
        <?php  else: ?>
			this.template = new Template(this.templateTextReadonly, this.templateSyntax);
        <?php endif; ?>

        this.numAttachments++;

        if (this.numAttachments == this.numAllowedAttachments) {
            this.addAttachmentBtn.hide();
        }

        if (this.numAttachments > this.numAllowedAttachments) {
            return;
        }

        if(!data.id){
            data = {};
            data.id  = 'id_'+new Date().valueOf();
            data.comment = '';
            data.file_name = '';
            data.url = '';
            data.updated_on = '';
            this.template = new Template(this.templateTextEdit, this.templateSyntax);
        }

        Element.insert(this.div, {'before':this.template.evaluate(data)});



        //set selected type
        if (data.type) {
            $A($('order-attachment_'+data.id+'_type').options).each(function(option){
                if (option.value==data.type) option.selected = true;
            });
        }

        //set selected is_require
        if (data.is_require) {
            $A($('order-attachment_'+data.id+'_is_require').options).each(function(option){
                if (option.value==data.is_require) option.selected = true;
            });
        }

        this.bindRemoveButtons();
    },
    remove : function(event){
        var element = $(Event.findElement(event, 'div'));
        if(element){
            $(element.readAttribute('id')+'_'+'is_delete').value = '1';
            element.addClassName('no-display');
            element.addClassName('ignore-validate');
            element.hide();
            this.numAttachments--;

            if (this.numAttachments < this.numAllowedAttachments) {
                this.addAttachmentBtn.show();
            }

        }
    },
    bindRemoveButtons : function(){
        var buttons = $$('div.attachment-box .delete-attachment');
        for(var i=0;i<buttons.length;i++){
            if(!$(buttons[i]).binded){
                $(buttons[i]).binded = true;
                Event.observe(buttons[i], 'click', this.remove.bind(this));
            }
        }
    }
}

orderAttachment.bindRemoveButtons();
if ($('add-attachment')) {
    Event.observe('add-attachment', 'click', orderAttachment.add.bind(orderAttachment));
}

<?php foreach ($attachments as $orderAttachment): ?>
    orderAttachment.add(<?php echo Mage::helper('core')->jsonEncode($orderAttachment) ?>);
<?php  endforeach; ?>
</script>