<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattach
 */
?>
<div id="viewblock_<?php echo $this->getItemCode(); ?>">
    <strong><?php echo htmlspecialchars($this->getItemValue()); ?></strong>
</div>

<div id="editblock_<?php echo $this->getItemCode(); ?>">

    <select id="value_<?php echo $this->getItemCode(); ?>">
        <?php if ($this->getOptions()): ?>
            <option value=""></option>
            <?php foreach ($this->getOptions() as $option): ?>
                <option
                    value="<?php echo $option; ?>" <?php if ($this->getItemValue() == $option) echo 'selected="selected"'; ?>><?php echo $option; ?></option>
            <?php endforeach; ?>
        <?php endif; ?>
    </select>
    
    <div style="margin-top: 2px;">
        <button class="scalable" type="button" onclick="javascript: attachSave('<?php echo $this->getItemCode(); ?>');">
            <span><?php echo $this->__('Save'); ?></span>
        </button>
        <!--
        <button class="scalable" type="button" onclick="javascript: attachCancel('<?php echo $this->getItemCode(); ?>');">
            <span><?php echo $this->__('Cancel'); ?></span>
        </button>
        -->
    </div>
</div>
