<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Orderattach
 */
?>
<div id="viewblock_<?php echo $this->getItemCode(); ?>">
    <?php if (Mage::app()->getRequest()->isAjax()): ?>
        <strong><?php echo nl2br($this->getItemValue()); ?></strong>
    <?php else: ?>
        <strong><?php echo nl2br(str_replace('$', '\$', htmlentities($this->getItemValue()))); ?></strong>
    <?php endif; ?>
</div>

<div id="editblock_<?php echo $this->getItemCode(); ?>" style="display: none;">
    <input id="value_<?php echo $this->getItemCode(); ?>" class="input-text"
           value="<?php echo htmlentities(preg_replace('/\$/', '\\\$', $this->getItemValue())); ?>"/>
    <div style="margin-top: 2px;">
        <button class="scalable" type="button" onclick="javascript: attachSave('<?php echo $this->getItemCode(); ?>');">
            <span><?php echo $this->__('Save'); ?></span>
        </button>
        <button class="scalable" type="button" onclick="javascript: attachCancel('<?php echo $this->getItemCode(); ?>');">
            <span><?php echo $this->__('Cancel'); ?></span>
        </button>
    </div>
</div>