<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleName = 'Team & Task Organizer For Magento';
$moduleVersion = '1.1.1';
$moduleRevision = '64915f73b29cfd0141ac79d7fe1f21dd73c7f3f7';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/Team_And_Task_Organizer_For_Magento';