<?php $customer = Mage::getSingleton('customer/session')->getCustomer();
$customerAllowed = Mage::helper('orderattachments')->getCustomersAllowed($customer);?>
<?php if ($customerAllowed):?>
	<?php $param = $this->getRequest()->getParam('order_id');?>
	<br/>
	<div class="order-items order-details">
		<h2><?php echo $this->__('Your Order Attachments')?> - <span><a href="<?php echo Mage::getUrl('orderattachments/attachment/manageattachments',array('order_id' => $param));?>"><?php echo $this->__('Manage Attachments');?></a></span></h2><br/>
		<?php $id = $this->getRequest()->getParam('order_id'); 
		$con = Mage::getModel('orderattachments/orderattachments')->getCollection()->addFieldToFilter('order_id',$id)
			->addFieldToFilter('visible_customer_account', 1)->setOrder('updated_on', 'desc');
		if(count($con)):?>
			<table class="data-table linearize-table-large">
				<thead>
					<tr class="first last">
						<th><?php echo $this->__('Created On');?></th>
						<th><?php echo $this->__('File');?></th>
						<th><?php echo $this->__('Comment');?></th>
					</tr>
				</thead>
				<tbody class="odd">
					<?php foreach($con as $val):?>
						<tr>
							<td><?php echo $this->formatDate($val->getCreatedOn(), 'medium', true) ?></td>
							<td><a target="_blank" href="<?php echo Mage::helper('orderattachments')->getPath().$val->getFile(); ?>"><?php echo basename($val->getFile());?></a></td>
							<td><?php echo $val->getComment();?></td>
						</tr>
					<?php endforeach;?>
				</tbody>
			</table>
		<?php else:?>
			<?php echo $this->__('You have no attachment uploaded')?> 
		<?php endif;?>
	</div>
<?php endif;?>