<?php $orderattachments = $this->getOrderattachments();?>
<?php 
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
	$customer = Mage::getSingleton('customer/session')->getCustomer();
	$customer_email = $customer->getEmail();
}
$collection = Mage::getModel('sales/order')->getCollection()
		->addAttributeToFilter('customer_email',array($customer_email));?>
<div class="page-title">
	<h2><?php echo $this->__('My Order Attachments')?></h2>
</div>

<?php
if($orderattachments->getSize() && count($collection)):?>
<?php echo $this->getPagerHtml();?>
	<table cellspacing="0" class="data-table linearize-table-large" id="attachment-table">
		<thead>
			<tr>
				<th><?php echo $this->__('Order #')?></th>
				<th><?php echo $this->__('Attachment Name')?></th>
				<th><?php echo $this->__('Comment')?></th>
				<th><?php echo $this->__('Created On')?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($orderattachments as $val):?>
				<?php $order = Mage::getModel('sales/order')->load($val->getOrderId());	?>
				<tr>
					<td><a href="<?php echo Mage::getUrl('sales/order/view/', array('order_id' => $val->getOrderId())); ?>"><?php echo $order->getIncrementId();?></a></td>
					<td><a target="_blank" href="<?php echo Mage::helper('orderattachments')->getPath().$val->getFile(); ?>"><?php echo basename($val->getFile());?></a></td>
					<td><?php echo $val->getComment() ?></td>
					<td><?php echo $this->formatDate($val->getCreatedOn(), 'medium');?></td>
				</tr>
			<?php endforeach;?>
		</tbody>
	</table>
	<script type="text/javascript">decorateTable('attachment-table')</script>
	<?php echo $this->getPagerHtml();?>			
<?php else:?>
	<p><?php echo $this->__('You have no order attachments.')?></p>
<?php endif?>