<?php
	//***************************** Params request to identify unique design mapped with a product*****************************
	$params = $this->getParams($_REQUEST);	
	if($params):		
		$designId 				= $params['did'];
		$mode					= $params['mode'];
	endif;	
	
	//***************************Customer Data*****************************
	$sessionId 					= Mage::helper('designersoftware/customer')->getCurrentSessionId();
	$customerId 				= Mage::helper('designersoftware/customer')->getCurrentCustomerId();
	$customerName				= Mage::helper('designersoftware/customer')->getCurrentCustomerName();	
		
	$url						= Mage::getBaseUrl();
	$baseWebUrl					= $this->getWebPath();
	
	// /js Path
	$jsPath				  		= $baseWebUrl . 'js' . DS . 'inky'  . DS;	
	$designerSoftwarePath 		= $jsPath . 'designersoftware' . DS;
	$imagesPath 				= $designerSoftwarePath . 'Skin' . DS . 'images'. DS; 
	
	// /media/inky Path
	$inkyPath					= $baseWebUrl . 'media' . DS . 'inky' . DS;
	
	
	// /media/inky/clipart Path
	$clipartPath				= $inkyPath . 'clipart' . DS;
	$clipartThumbPath			= $clipartPath . '224X224' . DS;
	$clipartOtherPath			= $clipartPath . 'original'. DS;
	
	// /media/inky/sizes Path
	$sizesPath				= $inkyPath . 'sizes' . DS;
	$sizesThumbPath			= $sizesPath . '224X224' . DS;
	$sizesOtherPath			= $sizesPath . 'original'. DS;
	
	
	// /media/inky/designs Path
	$designsPath				= $inkyPath . 'designs' . DS;
	$designsOriginal			= $designsPath . '{design_code}' . DS . 'original' . DS;
	$designs35x138				= $designsPath . '{design_code}' . DS . '35x138' . DS;
	$designs82x318				= $designsPath . '{design_code}' . DS . '82x318' . DS;
	
	
	// /media/inky/clipart_upload Path
	$uploadPath 				= $inkyPath . 'clipart_upload' . DS;
	$uploadOriginal				= $uploadPath . 'original' . DS;
	$upload51x53				= $uploadPath . '51X53' . DS;
	$upload224x224				= $uploadPath . '224X224' . DS;
	$uploadPrice				= Mage::helper('designersoftware/system_config')->getClipartUploadPrice();
	
	
	// /media/inky/font Path
	$fontPath					= $inkyPath . 'font' . DS;
	
	// /media/inky/font/image Path
	$fontImagePath				= $fontPath . 'image' . DS;
	$fontBoldImagePath			= $fontImagePath . 'bold' . DS;
	$fontItalicImagePath		= $fontImagePath . 'italic' . DS;	
	$fontBoldItalicImagePath	= $fontImagePath . 'bolditalic' . DS;	
	
	
	// /media/inky/font/ttf Path
	$fontTtfPath				= $fontPath . 'ttf' . DS;
	$fontBoldITtfPath			= $fontTtfPath . 'bold' . DS;
	$fontItalicTtfPath			= $fontTtfPath . 'italic' . DS;	
	$fontBoldItalicTtfPath		= $fontTtfPath . 'bolditalic' . DS;	
		
	
	/***************Part Access Path*********************/
	$layersPath=$inkyPath . 'parts_layers' . DS;
	
	
	// DesignerTool Tabs 
	// $defaultTabSelection		= Mage::getModel('designersoftware/system_config_source_default_tab')->getDefaultTab();
	// ********************Part Image Access Path*******************************/
	$productImageRatio			= '/235x440/';
	$previewImagePath			= '/290x540/';
	$mobileImagePath			= '/235x300/';		
?>	
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<title>Bootstrap 101 Template</title>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,100,200,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100italic,100,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<!-- Bootstrap -->
<link href="<?php echo $designerSoftwarePath;?>assets/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo $designerSoftwarePath;?>assets/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="<?php echo $designerSoftwarePath;?>assets/css/flexslider.css" type="text/css" media="screen" />
<link href="<?php echo $designerSoftwarePath;?>assets/css/style.css" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
 
<script>
	var site_url='<?php echo $designerSoftwarePath;?>';
	var site_path='<?php echo $baseWebUrl;?>';
	var dataAccessUrl='<?php echo $url;?>';
	var clip_art_path='<?php echo $clipartThumbPath;?>';
	var sizes_path='<?php echo $sizesThumbPath;?>';
	
	var normalTtf='<?php echo $fontTtfPath;?>';
	var boldTtf='<?php echo $fontBoldITtfPath;?>';
	var italicTtf='<?php echo $fontItalicTtfPath;?>';
	var boldItalicTtf='<?php echo $fontBoldItalicTtfPath;?>';
	
	var uploadThumb='<?php echo $upload51x53;?>';
	var uploadOriginal='<?php echo $uploadOriginal;?>';
	var uploadLarge='<?php echo $upload224x224;?>';
	var uploadPrice='<?php echo $uploadPrice; ?>';
	
	var layersPath='<?php echo $layersPath;?>';
	var productImageRatio='<?php echo $previewImagePath;?>';
	var previewImagePath='<?php echo $previewImagePath;?>';
	var uploadPrice='<?php echo $uploadPrice;?>';
	var mobileImagePath='<?php echo $mobileImagePath;?>';
	var mode='<?php echo $mode;?>';

	var designId='<?php echo $designId;?>';
	var sessionId='<?php echo $sessionId; ?>';
	var customerId='<?php echo $customerId; ?>';
	
	//alert(uploadPrice)
	//console.log(partPath)
	// alert(clip_art_path)
	//alert(site_url)
	//var site_path="http://124.124.87.46/INKY1003/"
	//console.l
</script>
