<?php
/* * ********************************************************************
 * Customization Services by ModulesGarden.com
 * Copyright (c) ModulesGarden, INBS Group Brand, All Rights Reserved 
 * (2014-10-31, 10:30:40)
 * 
 *
 *  CREATED BY MODULESGARDEN       ->        http://modulesgarden.com
 *  CONTACT                        ->       contact@modulesgarden.com
 *
 *
 *
 *
 * This software is furnished under a license and may be used and copied
 * only  in  accordance  with  the  terms  of such  license and with the
 * inclusion of the above copyright notice.  This software  or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person.  No title to and  ownership of the  software is  hereby
 * transferred.
 *
 *
 * ******************************************************************** */

/**
 * @author Grzegorz Draganik <grzegorz@modulesgarden.com>
 */
?>

<div class="modulesgarden_form_container">
	<div class="content-header skip-header">
		<h3 class="modulesgardenbase_config_header"><?php echo $this->__('Other Modules'); ?></h3>
	</div>
</div>

<div class="modulesgarden_grid_container">
    <div class="grid">
		<div class="hor-scroll">
			<table cellspacing="0" class="data">
                <thead>
					<tr class="headings">
						<th class=" no-link" style="width:50%;"><span class="nobr"><?php echo $this->__('Extension Name'); ?></span></th>
						<th class=" no-link"><span class="nobr"><?php echo $this->__('Your Version'); ?></span></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->getExtensions() as $k => $extension) { ?>
						<tr class="<?php echo $k%2==0 ? 'even' : ''; ?>">
							<td class="a-left"><?php echo $extension->getName(); ?></td>
							<td class="a-left last"><?php echo $extension->getVersion(); ?></td>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>

