<?php

/**********************************************************************
 * Customization Services by ModulesGarden.com
 * Copyright (c) ModulesGarden, INBS Group Brand, All Rights Reserved 
 * (2014-10-31, 13:03:09)
 * 
 *
 *  CREATED BY MODULESGARDEN       ->        http://modulesgarden.com
 *  CONTACT                        ->       contact@modulesgarden.com
 *
 *
 *
 *
 * This software is furnished under a license and may be used and copied
 * only  in  accordance  with  the  terms  of such  license and with the
 * inclusion of the above copyright notice.  This software  or any other
 * copies thereof may not be provided or otherwise made available to any
 * other person.  No title to and  ownership of the  software is  hereby
 * transferred.
 *
 *
 **********************************************************************/

/**
 * @author Grzegorz Draganik <grzegorz@modulesgarden.com>
 */
$defaultIcon = Mage::getBaseUrl('skin') . '/adminhtml/base/default/modulesgardenbase/img/icons/module.png';
?>

<div class="modulesgarden_grid_container mg_store_container">
	<table class="extension" cellspacing="0">
	<?php foreach ($this->getExtensions() as $extension){ ?>
            <tr>
                    <td class="img">
                            <img src="<?php echo $extension->getIconUrl($defaultIcon); ?>" />
                    </td>
                    <td class="content">
                            <h3><a href="<?php echo $extension->getFeaturesUrl(); ?>" target="_blank"><?php echo $extension->getFriendlyName(); ?></a></h3>
                            <small>Version <?php echo $extension->getLatestVersion(); ?></small>

                            <div>
                                <?php if ($extension->isAlreadyInstalled()){ ?>
                                    <span class="storelabel installed"><?php echo $this->__('Already Installed'); ?></span>
                                <?php } ?>
                                <?php if ($extension->getIsNew()){ ?>
                                    <a class="storelabel new" href="<?php echo $extension->getChangelogUrl(); ?>" target="_blank"><?php echo $this->__('New Version Available'); ?></a>
                                <?php } ?>
                                <?php if ($extension->getIsPromotion()){ ?>
                                    <span class="storelabel promotion"><?php echo $this->__('Promotion'); ?></span>
                                <?php } ?>
                            </div>

                            <p class="description"><?php echo $extension->getDescription(); ?></p>
                    </td>
                    <td class="price">
                            <?php if ($extension->getPrice() > 0){ ?>
                                    <strong>$<?php echo $extension->getPrice(); ?></strong>
                                    <a href="<?php echo $extension->getBuyUrl(); ?>" class="form-button" target="_blank"><?php echo $this->__('Buy Now'); ?></a>
                            <?php } else { ?>
                                    <strong><?php echo $this->__('FREE'); ?></strong>
                                    <a href="<?php echo $extension->getFeaturesUrl(); ?>" class="form-button" target="_blank"><?php echo $this->__('Download'); ?></a>
                            <?php } ?>
                    </td>
            </tr>
	<?php } ?>
	</table>
</div>

<script type="text/javascript">
document.observe("dom:loaded", function() {
	// simple fix for "save" button color
	$$('.form-buttons').invoke('addClassName', 'modulesgarden_form_container');
});
</script>