<div class="content-header">

    <table cellspacing="0">

        <tr>

            <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('catalog')->__('Manage Leadtimes') ?></h3></td>

            <td class="a-right">

                <?php echo $this->getButtonsHtml() ?>

            </td>

        </tr>

    </table>

</div>



<form id="leadtimes_form" method='post' action=''>

    <?php echo $this->getGridHtml() ?>

</form>