<!doctype html>
<title>JBcases Maintenance mode</title>
<style>
  body { text-align: center; padding: 120px; }
  h1 { font-size: 50px; }
  body { font: 20px Helvetica, sans-serif; color: #333; }
  article { display: block; text-align: center; width: 650px; margin: 0 auto; }
  a { color: #dc8100; text-decoration: none; }
  a:hover { color: #333; text-decoration: none; }
</style>
 
<article>
	<img src="<?php echo $this->getSkinUrl();?>images/logo.png" class="logo-image" alt="JB Cases" width="300px">
    <h1>We'll be back soon!</h1>
    <div>
        <p>Sorry for the inconvenience but <b>JB Cases</b> is performing some maintenance at the moment. If you need to you can always <a href="mailto:support@jbcases.com">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
        <p>Visit our <a href="https://www.facebook.com/JBCustomCueCASES/">Fanpage</a>
 for updating news and tutorial</p>
        <p>&mdash; JB Cases</p> 
    </div>
</article>
