<?php
/**
 * SAGIPL
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category   	SAGIPL
 * @package	Sag_Shippingmessage
 * @copyright  	Copyright (c) 2014 SAGIPL. (http://www.sagipl.com/)
 * @license	http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Free Shipping Message
 *
 * @category	SAGIPL
 * @package	Sag_Shippingmessage
 * @author	Navneet <navneet.kshk@gmail.com>
 */

	$message = $this->getShippinmessage();
	if($message!=''){
?>

<style>
	.message{ border:2px solid #CC0; 
			border-radius:5px; 
			padding:5px; 
			background:#1f3241; 
			text-decoration: none; 
			font-weight:bold; 
			font-size:16px; 
			margin:5px; 
			display: block; 
			float:left;
			-webkit-animation: spaceboots 2s linear infinite;
			 -moz-animation: spaceboots 2s linear infinite;
			 -ms-animation: spaceboots 2s linear infinite;
			 animation: spaceboots 2s linear infinite;
			 color:#f63c43;
		}
		
		@keyframes spaceboots {
			0% { transform: translate(2px, 1px) rotate(0deg); }
			10% { transform: translate(-1px, -2px) rotate(-1deg); }
			20% { transform: translate(-3px, 0px) rotate(1deg); }
			30% { transform: translate(0px, 2px) rotate(0deg); }
			40% { transform: translate(1px, -1px) rotate(1deg); }
			50% { transform: translate(-1px, 2px) rotate(-1deg); }
			60% { transform: translate(-3px, 1px) rotate(0deg);}
			70% { transform: translate(2px, 1px) rotate(-1deg); }
			80% { transform: translate(-1px, -1px) rotate(1deg); }
			90% { transform: translate(2px, 2px) rotate(0deg); }
			100% { transform: translate(1px, -2px) rotate(-1deg); }
		}
		
		@-webkit-keyframes spaceboots {
			0% {  -webkit-transform: translate(2px, 1px) rotate(0deg); }
			10% { -webkit-transform: translate(-1px, -2px) rotate(-1deg); }
			20% { -webkit-transform: translate(-3px, 0px) rotate(1deg); }
			30% { -webkit-transform: translate(0px, 2px) rotate(0deg); }
			40% { -webkit-transform: translate(1px, -1px) rotate(1deg); }
			50% { -webkit-transform: translate(-1px, 2px) rotate(-1deg); }
			60% {  -webkit-transform: translate(-3px, 1px) rotate(0deg);}
			70% { -webkit-transform: translate(2px, 1px) rotate(-1deg); }
			80% { -webkit-transform: translate(-1px, -1px) rotate(1deg); }
			90% { -webkit-transform: translate(2px, 2px) rotate(0deg); }
			100% { -webkit-transform: translate(1px, -2px) rotate(-1deg); }
		}
</style>

<div class="message"><?php echo $message;?></div>
<?php }  ?>